//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120_Waste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int articleId { get; set; }
        public string articleName { get; set; }
        public int Waste_wasteId { get; set; }
    
        public virtual Waste Waste { get; set; }
    }
}
