//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120_Waste.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIT5120_ModelContainer : DbContext
    {
        public FIT5120_ModelContainer()
            : base("name=FIT5120_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Waste> WasteSet { get; set; }
        public virtual DbSet<WasteKind> WasteKindSet { get; set; }
        public virtual DbSet<Article> ArticleSet { get; set; }
    }
}
